language: node_js
node_js:
 - "12"
install:
 - 'npm install'
jdk:
 - oraclejdk8
addons:
 sonarcloud: true
script:
 - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=dbotia-github -Dsonar.projectKey=lab22021 -Dsonar.sources='./app' -X
